title: Pitch Changer
url: https://pitch-changer.com
baseurl: ""
default_locale: en
locales:
  - en
  - it
  - es
  - de
  - fr
  - ja
  - ru
  - uk
  - ko
  - nl
  - sv
  - nb
  - da
  - pl
  - pt
  - zh-TW
